import CashierTemplate from "@/components/cashierTemplate"
import CahsierList from "../../cashierList"

export const metadata = {
    title: 'Program | Ordering System',
    description: 'Generated by create next app',
}

type PropsLayout = {
    children: React.ReactNode
}

const RootLayout = ({ children }: PropsLayout) => {
    return (
        <CashierTemplate title="Program" id="program" menuList={CahsierList}>
            {children}
        </CashierTemplate>
    )
}

export default RootLayout